# Generated by Django 2.0.1 on 2018-01-18 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.IntegerField()),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('x_Coordinate', models.FloatField()),
                ('y_Coordinate', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='observation',
            name='survey_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.SurveyPoint'),
        ),
    ]
